#+TYP_TODO: ISSUE | FIXED

* ISSUE Multiple runtimes

If we're having multiple languages, then each language must define its own
runtime. But how do we manage all of these different runtimes when building?

Currently every module is parameterised on a root runtime. The root runtime
provides a =selectRuntime(languageIdentifier)= method, that's called to
choose the runtime for that module, and it's up to the root runtime to
figure out how to translate these language identifiers to actual runtime
services.

Things that still need figuring out:

- How do we make sure that runtimes can't conflict?
- Should we have the language describe which runtime it's using? Do we support this in Core?


* ISSUE Incremental parsing

How do we handle incremental parsing for the languages when working in
the IDE?


* ISSUE Canel.és is fundamentally incompatible with existing tooling

Because nothing out there (text editors, github, etc) support this kind of
multi-language language.

* ISSUE Which services should Layers provide?

Mapping compiled code to source, highlighting, formatting, linting.

Can we support this with the grammar language?


